name: Release

on:
  release:
    types: [published]

jobs:

  release_zip:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Zip mikrotik_router dir
        run: |
          cd "${{ github.workspace }}/custom_components/mikrotik_router"
          zip mikrotik_router.zip -r ./

      - name: Upload zip to release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ github.workspace }}/custom_components/mikrotik_router/mikrotik_router.zip

  releasenotes:
    name: Prepare releasenotes
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install requirements
        run: |
          python3 -m pip install setuptools wheel PyGithub

      - name: Update release notes
        run: |
          python3 "${{ github.workspace }}/.github/generate_releasenotes.py" --token ${{ secrets.GITHUB_TOKEN }} --release yes --tag ${{ github.ref }}
